# Generated by Django 2.2.dev20180619125833 on 2018-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Street Name'),
        ),
    ]
