# Generated by Django 2.2.dev20180619125833 on 2018-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_address_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_cardinal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Cardinal'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_class',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Class'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zip Code'),
        ),
    ]
