# Generated by Django 2.2.dev20180619125833 on 2018-06-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180622_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_as_contact_set', to='contacts.Contact', verbose_name='contact'),
        ),
    ]
