# Generated by Django 2.2.dev20180619125833 on 2018-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20180622_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='testfield',
            field=models.CharField(default='test', max_length=255, verbose_name='test'),
        ),
    ]
