# Generated by Django 2.2.dev20180619125833 on 2018-06-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='testfield',
        ),
    ]
