# Generated by Django 2.2.dev20180619125833 on 2018-06-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20180622_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='quantity_per',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10, verbose_name='Quantity Per'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_as_subunit_set', to='units.Unit', verbose_name='subunit'),
        ),
    ]
