# Generated by Django 2.2.dev20180619125833 on 2018-06-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20180622_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='units.Unit', verbose_name='subunit'),
        ),
    ]
