# Generated by Django 2.2.dev20180619125833 on 2018-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('account_number', models.CharField(max_length=255, verbose_name='Account Number')),
                ('card_number_last4', models.CharField(max_length=255, verbose_name='Card Number (last 4 digits)')),
            ],
        ),
    ]
