# Generated by Django 2.2.dev20180619125833 on 2018-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='card_number_last4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Card Number (last 4 digits)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Account Name'),
        ),
    ]
