# Generated by Django 2.2.dev20180619125833 on 2018-06-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_subunit'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericitem',
            name='base_unit_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genericitem_as_base_unit_custom_set', to='units.Unit'),
        ),
        migrations.AddField(
            model_name='genericitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Unit'),
        ),
        migrations.AddField(
            model_name='genericitem',
            name='unit_factor_custom',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10, verbose_name='Custom Unit Factor'),
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Unit', verbose_name='item_as_base_unit_custom_set'),
        ),
        migrations.AddField(
            model_name='item',
            name='generic_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_as_generic_item_set', to='items.GenericItem', verbose_name='generic item'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_as_unit_set', to='units.Unit'),
        ),
    ]
