# Generated by Django 2.2.dev20180619125833 on 2018-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180621_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Model/Item Number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(blank=True, max_length=255, verbose_name='UPC Code'),
        ),
    ]
