# Generated by Django 2.2.dev20180619125833 on 2018-06-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180622_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qty_test',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10, verbose_name='Qty (Test)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='base_unit_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_as_base_unit_custom_set', to='units.Unit', verbose_name='custom base unit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='generic_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_as_generic_item_set', to='items.GenericItem', verbose_name='generic item'),
        ),
    ]
