# Generated by Django 2.2.dev20180619125833 on 2018-06-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180628_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_factor_custom',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, verbose_name='Custom Unit Factor'),
        ),
    ]
