# Generated by Django 2.2.dev20180619125833 on 2018-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('total_custom', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custom Total')),
                ('tax_total_custom', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custom Tax Total')),
                ('tip_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tip Total')),
                ('bags_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bags Total')),
                ('donation_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Donation Total')),
                ('grand_total_custom', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custom Grand Total')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Quantity')),
                ('price_regular_custom', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Custom Regular Price')),
                ('discount_custom', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Custom Discount')),
                ('price_discounted_custom', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Custom Discounted Price')),
                ('price_extended_custom', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Custom Extended Price')),
                ('crv_per_custom', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Custom CRV Per')),
                ('tax_per_custom', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Custom Tax Per')),
            ],
        ),
    ]
