# Generated by Django 2.2.dev20180619125833 on 2018-06-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0003_address_contact'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_account_from_set', to='accounts.Account', verbose_name='from account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_account_to_set', to='accounts.Account', verbose_name='to account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_address_set', to='contacts.Address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_contact_custom_set', to='contacts.Contact', verbose_name='custom contact'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactiondetail_as_transaction_set', to='transactions.Transaction'),
        ),
    ]
