# Generated by Django 2.2.dev20180619125833 on 2018-06-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180624_1656'),
        ('transactions', '0003_auto_20180622_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='generic_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactiondetail_as_generic_item_set', to='items.GenericItem', verbose_name='generic item'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactiondetail_as_item_set', to='items.Item'),
        ),
    ]
