# Generated by Django 2.2.dev20180619125833 on 2018-06-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180627_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_account_from_set', to='accounts.Account', verbose_name='from account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_account_to_set', to='accounts.Account', verbose_name='to account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_address_set', to='contacts.Address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bags_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Bags Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contact_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_contact_custom_set', to='contacts.Contact', verbose_name='custom contact'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='donation_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Donation Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='grand_total_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Custom Grand Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_total_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Custom Tax Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tip_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Tip Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Custom Total'),
        ),
    ]
