# Generated by Django 2.2.dev20180619125833 on 2018-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20180628_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bags_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bags Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='donation_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Donation Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='grand_total_custom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custom Grand Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_total_custom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custom Tax Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tip_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tip Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_custom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custom Total'),
        ),
    ]
