# Generated by Django 2.2.dev20180619125833 on 2018-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20180628_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='crv_per_custom',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Custom CRV Per'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='discount_custom',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Custom Discount'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='price_discounted_custom',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Custom Discounted Price'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='price_extended_custom',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Custom Extended Price'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='price_regular_custom',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Custom Regular Price'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='tax_per_custom',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Custom Tax Per'),
        ),
    ]
